### ISSUE TITLE
Collapse level behavior seems to be changed

### ISSUE THREAD

**Issue by monoblaine** [triforcely/CollapseLevel#3]
First of all, thanks for open-sourcing this extension! Today, I realized that `Alt + 1` no longer works the way it used be. Than I realized that the extension was auto-updated to version 2.0.0, and I also realized that it was open-sourced. And here I am :)

`View.Level1collapse` used to change the following file:

```js
function foo () {
    // code
}

function bar () {
    // more code
}
```

into this:

```
[+] function foo () [...]

[+] function bar () [...]
```

But starting with version 2.0.0, the only way to do this is to apply a custom level (zero).

Was this change intentional?

I've removed some line to restore the original behavior:

https://github.com/monoblaine/CollapseLevel/commit/16a64a5664b8f66cf3ab1f9db16838c5fd635849

**Comment by triforcely** [comment]
Thanks for creating this issue Serhan, I'm glad that I opensourced this extension, so issues like this can be quickly discovered and resolved 😄 

After initial release I was really busy with other things and I left some changes in the project. Since it wasn't versioned at all, I just overlooked it. This shouldn't happen anymore since it is now hosted on GitHub.

I think that level 0 isn't really intuitive and most likely everyday users are confused by this change in functionality, so let's merge your change.

Please, create PR - I'll be happy to accept it  🙂
